version: '3.8'

services:
  # Postgres database for inventory
  db-inventory:
    container_name: db-inventory
    image: postgres:15.4
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_inventory
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5430:5430"
    expose:
      - "5430"
    command: -p 5430

  # MySQL database for order
  db-orders:
    container_name: db-orders
    image: mysql:8.1.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ms_orders
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    expose:
      - "3306"

  # Postgres database for products
  db-products:
    container_name: db-products
    image: postgres:15.4
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_products
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5431:5431"
    expose:
      - "5431"
    command: -p 5431